[package]
name = "image_scraper"
version = "0.1.0"
edition = "2021"
license = "MIT"
keywords = ["google", "images"]
description = "A crate used to search Google Images based on provided arguments."
homepage = "https://www.github.com/jibble330/image_scraper"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.13", features = ["blocking"]}
infer = "0.11.0"
glob = "0.3.0"
serde_json = "1.0.88"
